# Test against this version of Node.js
environment:
  nodejs_version: "10"
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ

# only build master (currently this is the only way to avoid the build failing on other branches)
branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm config set loglevel warn
  - npm install --silent

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cmd: try npm run lint
  - cmd: try npm run test

build_script:
 - cmd: try node build/patch-fse-semicolons.js

before_build:
 - git checkout master

on_success:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "bbbbbbenes@outlook.com.br"
 - git config --global user.name "Appveyor Automated Build"
 # run coverage
 #- cmd: try npm run coverage
 # set datetime vars
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a%%b)
 # commit fixed semicolons
 - cmd: addall js
 - cmd: try git commit -m "Fixed semicolons at %mydate%_%mytime% [skip ci]"
 # gen fse typings docs
 - cmd: node build/gen-fse-definitions
 - cmd: add fs-extra.d.ts
 - cmd: try git commit -m "Generated type definitions at %mydate%_%mytime% [skip ci]"
 # commit new docs
 - cmd: gen-typedocs
 - cmd: add docs/typedoc
 - cmd: add docs/typedoc-fsxt-only
 - cmd: try git commit -m "Generated docs at %mydate%_%mytime% [skip ci]"
 # push
 - git push origin master

notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: +5y63VhkKwOZVK264xwgH8gp7vI2cJivXvseQeSoYYNyH3wjOtid8Qz+gyNOjCGpI/xqxxJNwqFrL75ZPHYOYEKs9WhBWznTsFpJUAs5hxn1kcczMv6WYuwUzXJNEdqX6m47PnS7xrzUZJIRWNQCHRJCtN5VX+hXfVV6BT+tKQdRDeRr/LANhRLr2pAbIOGP
