sudo: false
language: node_js
matrix:
  include:
    # We run lint, unit and coverage on Node 8
    - node_js: "10"
      env: TEST_SUITE=test
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
after_success:
  - if [ $TEST_SUITE = coverage ]; then npm run coveralls; fi
